const DEFAULT_SETTINGS = {
  password : "raidisnotabackup",
  slideDuration : 10,
  playThemes : "true",
  genericThemes : "true",
  fade : "true",
  hideSettingsLinks : "false",
  theaterRoomMode : "false",
  mediaServerType : "plex",
  plexIP : "",
  plexHTTPS : "false",
  plexPort : 32400,
  plexToken : "",
  pinNS : "false",
  hideUser: "false",
  onDemandLibraries : "",
  numberOnDemand : 2,
  onDemandRefresh : 30,
  sonarrURL : "",
  sonarrToken : "",
  sonarrCalDays : 3,
  sonarrPremieres : "false",
  radarrURL : "",
  radarrToken : "",
  radarrCalDays : 30,
  lidarrURL : "",
  lidarrToken : "",
  lidarrCalDays : 30,
  readarrURL : "",
  readarrToken : "",
  readarrCalDays : 60,
  /** "readarr" | "chaptarr" — same API; used for UI and log labels */
  bookArrKind : "readarr",
  hasArt : "false",
  /** When true, show principal cast (actors) on media cards when metadata includes it */
  showCast: "false",
  showDirectors: "false",
  showAuthors: "false",
  /** Album / track artist line when metadata provides it (music) */
  showAlbumArtist: "false",
  /** Show main cover poster for music (album / track) cards */
  displayPosterAlbum: "true",
  /** Show main poster for movie and TV cards (movie / episode / show) */
  displayPosterVideo: "true",
  /** Show main cover poster for ebooks and audiobooks cards */
  displayPosterBooks: "true",
  /** Small portrait image from first cast member with art (Plex / Jellyfin / Emby) */
  displayPosterActor: "false",
  /** Second cast portrait on Plex; Jellyfin/Emby prefers a female actor when Gender is set */
  displayPosterActress: "false",
  displayPosterDirector: "false",
  displayPosterAuthor: "false",
  /** Album / track artist portrait when the server provides separate art */
  displayPosterArtist: "false",
  shuffleSlides: "false",
  genres: "",
  custBrand: "",
  titleColour: "#FAFAD2",
  footColour: "#FAFAD2",
  bgColour: "#000000",
  enableNS: "true",
  enableOD: "true",
  enableSonarr: "true",
  enableRadarr: "true",
  enableLidarr: "true",
  enableReadarr: "true",
  filterRemote: "true",
  filterLocal: "true",
  filterDevices: "",
  filterUsers: "",
  odHideTitle: "false",
  odHideFooter: "false",
  enableCustomPictures: "false",
  enableCustomPictureThemes: "false",
  customPictureTheme: "default",
  serverID: "",
  sleepStart: "00:00",
  sleepEnd: "07:00",
  enableSleep: "false",
  nowScreening: "",
  comingSoon: "",
  onDemand: "",
  recentlyAdded: "",
  recentlyAddedDays: "0",
  iframe: "",
  playing: "",
  ebook: "",
  trivia: "",
  triviaFrequency: 300,
  triviaTimer: 15,
  triviaCategories: "",
  enableTrivia: "false",
  triviaNumber: "",
  contentRatings: "",
  enableAwtrix: "false",
  awtrixIP: "",
  enableLinks: "false",
  links: "",
  excludeLibs: "",
  /** Minutes between poster DB/cache refresh checks; 0 = disabled. Stale entries re-download from stored URL or are dropped. */
  posterCacheRefreshMins: 0,
  /** Minimum minutes since a poster row was last updated before we check the media server for removal or re-download the image. 0 = no extra wait (only the refresh interval applies to image checks). */
  posterCacheMinAgeBeforeChangeCheckMins: 0,
  /** When true, slideshow library slides come from poster cache/DB first; live on-demand from the media server is only a backup and still fills the cache. */
  preferCachedPosters: "true",
  /** How many cached poster slides to build when preferCachedPosters is on (actual deck is at most entries in the poster DB). */
  cachedPosterSlideCount: 48
};

module.exports = DEFAULT_SETTINGS;